### ISSUE TITLE
PIPL03, ubuntu version- v2_test, Structure PDF not getting generated

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/SyMoG#1]
Machine- PIPL03
Version- v2_test

In case of export structure (image, PDF)-  Images get downloaded instantly but PDF does not. tried with two sets of inputs.
Wait period- almost 20minutes.

![Capture](https://user-images.githubusercontent.com/111036161/184299862-61d565ae-7aa7-4110-bcc9-e6fa98808e1e.JPG)
![PDF download time](https://user-images.githubusercontent.com/111036161/184299867-3680189c-c763-4564-b5a5-95ec62ee5c45.JPG)

**Comment by LobeliaG** [comment]
PIPL01- PDF is not getting generated in Windows system as well.

**Comment by mdaakhan** [comment]
bug fixed commit id [0eef40e] 
![Screenshot 2022-08-19 155626](https://user-images.githubusercontent.com/69871502/185599717-12c6ce0b-f3de-4a3c-9ed3-b646190b3bcd.png)
