### ISSUE TITLE
Suggestions - input & output results download

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/SyMoG#10]
Windows - PRinS_Installer_WIN10_x64
version - latest v 2.0.0

1] **Export PDB** option given in the output side downloads the selected smiles and pdbs from both input and output. This can be confusing for user because he might not be aware that both the results are getting downloaded.
Suggestion- The placement of **Export PDB** can be changed or the naming can be changed. 

2] The **export generated smiles** and **export input smiles** option downloads every smiles irrespective of the selection. If the user selects few smiles on the basis of score and those selected smiles are not getting downloaded then it can be confusing.
Suggestion- The naming can be changed or a hover text can be added saying _download all smiles_.

![symogai](https://user-images.githubusercontent.com/117424735/211508872-169e6456-2f40-45f8-9b02-774fef4c0925.png)

**Comment by mdaakhan** [comment]
Fixed in Bundel V_2_1_0
