### ISSUE TITLE
SyMoG - Generate PDB Files - not generating files 

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/SyMoG#2]
Hi,

In SyMoG and ChemIn, sometimes Generate PDB files keeps running for longer times and actually not generating files. Only creating blank folders.
We need to keep check at this place - 'system time out' after certain amount of time. 
![Screenshot from 2022-05-27 15-59-12](https://user-images.githubusercontent.com/105902516/170686108-8584d9a8-5b9f-419f-a6cc-cc9e4a8efa9a.png)

**Comment by mdaakhan** [comment]
bug fixed commit id [0eef40e] 
![Uploading Screenshot 2022-08-19 155626.png…]()
