### ISSUE TITLE
PIPL01- software crashes on PDB generation

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/SyMoG#3]
Machine- PIPL01
windows version- PRiNS_v2.exe

From the output page there is no problem in PDB generation. But When I try to **generate PDB files from scaffold page**, the software crashes.

**Comment by mdaakhan** [comment]
bug fixed commit id [0eef40e] 
![Screenshot 2022-08-19 155626](https://user-images.githubusercontent.com/69871502/185599501-6e2401db-0316-46fc-9b88-ec6346c0eed6.png)

**Comment by LobeliaG** [comment]
Same issue happening again. When I try to generate PDB files from scaffold page, the software crashes.
**Machine- PIPL01, software version-  PRiNS_D_V_2_0_2_windows**

**Comment by mdaakhan** [comment]
Checked in PIPL01 IT WENT well
![Screenshot from 2022-08-26 15-12-16](https://user-images.githubusercontent.com/69871502/186876607-346aee4f-28ee-4f31-ad21-e46b05920573.png)
