### ISSUE TITLE
Input File - If contains extra empty line - SyMoG doesn't throw error

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/SyMoG#4]
hi,

If I keep my input file one empty line at the end, symog takes it as input but cannot process it. It should throw some error/pop-up saying wrong input.

**Comment by SumedhaBhosale** [comment]
In fact, for all types of wrong inputs - it doesn't throw error ! 
For e.g. SMI file we usually get from any database is smile column with database ID or compound name tab separated or comma-separated. SyMoG takes input but cannot process them. It should throw error/pop-up saying "Wrong Input or check input file"

**Comment by LobeliaG** [comment]
Yes. If there is any space before or after the lines containing SMILEs or if there is any gap line between any two lines of the file, the app cannot process those. However it can process the files which have any space before or after the SMILEs in the same line. No pop-up warnings for any of these situations though.

**Comment by mdaakhan** [comment]
Fixed
v1: f7aa542
v2: 0ef0bf0
