### ISSUE TITLE
Error pop-up when trying to generate tanimoto report

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/SyMoG#5]
machine- PIPL01
software - windows- hackathon version

Error pop up comes up when we try to generate tanimoto report. But the file is generated in the folder.  Inputs were taken from ChemIn.
[tanimoto.csv](https://github.com/chandkc/SyMoG/files/9572688/tanimoto.csv)
[input.txt](https://github.com/chandkc/SyMoG/files/9572715/input.txt)

![image](https://user-images.githubusercontent.com/111036161/190337125-a5eeebf9-3aeb-453f-b63a-166ddfab2e65.png)

**Comment by mdaakhan** [comment]
Fixed in Bundel V_2_0_0
