### ISSUE TITLE
PrinChem to ChemIn 

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/SyMoG#9]
**PRinS_Ubuntu_20_86X64_2_0_0**

PrinChem should be changed to ChemIn 

![Screenshot from Screencast from 28-11-22 01:09:01 PM IST webm - 1](https://user-images.githubusercontent.com/117424735/204222521-aa88b4fd-a3f5-4779-9ce6-4c3a5e0783ef.png)

**Comment by mdaakhan** [comment]
Fixed in Bundel V_2_1_0
